### ISSUE TITLE
One-click to copy JSON to clipboard

### ISSUE THREAD

**Issue by tyhicks** [Vulnogram/Vulnogram#10]
The JSON output by Vulnogram is typically copy and pasted elsewhere such as a text editor, email client, etc. It would be nice if there was a single button to click in order to copy the JSON into the clipboard rather than having to highlight the JSON before copying it.

**Comment by chandanbn** [comment]
That is a good idea. Thank you!

Would a download link, that could save the JSON as a text file to filesystem be more useful? and reduce clicks/keystrokes needed to get work done? perhaps I can add icon buttons for both.

If the purpose of copying is to eventually commit it to a git repo for submitting a pull request to cvelist repo, perhaps a button that says "Sync to my git repo" or "Submit to CVE list" would be desirable.

Git/github integration is in the roadmap.

**Comment by tyhicks** [comment]
Interesting idea. I'm not sure which one I'd use more between the "copy to clipboard" and "save" buttons. I think that either would improve the current workflow. Both could be nice as long as it doesn't complicate the graphical interface too much.

**Comment by chandanbn** [comment]
JSON tab now shows Copy and Download buttons.
