### ISSUE TITLE
Histories stored in wrong table

### ISSUE THREAD

**Issue by iamamoose** [Vulnogram/Vulnogram#106]
Reported by email but creating an issue to remember it.  Histories are being stored in the nvd_histories table instead of the right cve_histories or cve5_histories model table.  So while histories appear to be working for new entries, histories from before 0.1.0 are not found/shown.

Note once fixed histories will need to be moved/merged out of the nvd_histories table.

**Comment by chandanbn** [comment]
While this got fixed in code, a mongo script is needed to go through every _history collection and move the diff info and comments to the right collection to completely fix this.
