### ISSUE TITLE
Is it possible to sort the attributes in JSON alphabetically

### ISSUE THREAD

**Issue by MrSeccubus** [Vulnogram/Vulnogram#107]
When you create a JSON5.0 record via Vulnogram the attributes in the JOSN file are in a certain order, but when you upload your record to the CVE Services with CVE Lib and then retreive them, the attributes are sroted alphabetically.

Would it be possible for Vulnogram to use this same sorting of attributes?

This way it bacomes a lot easier to diff records form CVE lib with those form Vulnogram.

**Comment by chandanbn** [comment]
Clicking the download button does this. The JSON source editor view tab is for editing only. You should not copy paste JSON from that window and submit through CLI or other mechanisms. Use the download button to get the file.

Having the same order as in the GUI is more intuitive in the source editor view. Once you click export/download/publish button, it generates the equivalent of JSON from the CVE API. i.e., (1) fields in alphabetical order (2) minimized JSON removing empty fields.
