### ISSUE TITLE
Extending Vulnogram to support OSV

### ISSUE THREAD

**Issue by andrewpollock** [Vulnogram/Vulnogram#129]
Hi, this is a random thought that popped into my head just now, and I wanted to get it out of my head...

I wanted to socialise the idea of extending vulnogram to support emitting an OSV-format record, and get a sense of the acceptability of such a contribution if effort were to be expended making it.

Alternatives would be forking vulnogram, or creating something from scratch in the spirit of vulnogram...

/cc @oliverchang

**Comment by chandanbn** [comment]
You can create a Vulnogram plugin (not well documented) with OSV schema and drop it in the "custom" directory.
The schema may have to be embellished with some UI hints for better layout and usability. You will get an instant OSV editor.

See other plugins for example:
https://github.com/Vulnogram/plugins/blob/697f979389a5ba10fb42ae6d34cf7adbea3234ac/custom/contact/conf.js#L25
