### ISSUE TITLE
Pre-populate the description field with the version information.  

### ISSUE THREAD

**Issue by mlhess** [Vulnogram/Vulnogram#15]
Since we fill out the version field then the description field, could we pre-populate  the version text in the description.  

In product version name  Before Version_String .... 

etc

**Comment by chandanbn** [comment]
That is what should happen when you click the green "Auto-Text" button above the description field. It will take the information from other fields and try to fill in the description using a template.

**Comment by mlhess** [comment]
+1 Amazing!
