### ISSUE TITLE
List of CAPEC impacts may be outdated

### ISSUE THREAD

**Issue by openmorse** [Vulnogram/Vulnogram#164]
The Vulnogram list of CAPEC impacts seems to not be current.

![capec-list](https://github.com/Vulnogram/Vulnogram/assets/26353417/576f2947-4c26-4bbb-a73a-90b727cae2a7)

The [current CAPEC list here](https://capec.mitre.org/data/index.html) does not contain those entries, e.g. searching for CAPEC-546 on the CAPEC site results in an error.

![capec-id-error](https://github.com/Vulnogram/Vulnogram/assets/26353417/82b3b50c-7ca4-42b4-8e91-9e1e2b025de4)

**Comment by chandanbn** [comment]
fixed
