### ISSUE TITLE
Disallow multiple problem types?

### ISSUE THREAD

**Issue by todb-r7** [Vulnogram/Vulnogram#17]
Hi @chandanbn ! A little while ago, I got a CVE rejected due to multiple entries on the problemtype:

https://github.com/CVEProject/cvelist/pull/1953#pullrequestreview-232205765

Namely, `A language tag was used multiple times: problemtype value #0`

Near as I can tell, the CVE autovalidator doesn't like multiple problemtypes, so can we make this illegal in vulnogram?

**Comment by chandanbn** [comment]
We had stumbled upon this error too once. Most validation built into vulnogram is just what comes with the schema rules. MITRE recently added some outside validation that is not encoded in the schema.

Workaround:
The problemtype field is an array of arrays. To add multiple problem types you have to click "add problem type" button and not "Add problem type description". 

"Problem type description" was meant for descriptions in multiple languages for the same problem type.

I'll fix this by updating the schema.

**Comment by chandanbn** [comment]
This is now fixed by removing the "Add problem type description" button. This should prevent CNAs from entering multiple descriptions for a single problem type via the GUI. One can still add multiple problem types, and the JSON would still be valid.
