### ISSUE TITLE
opening stand-alone index.html doesn't work

### ISSUE THREAD

**Issue by ericjohnson-tibco** [Vulnogram/Vulnogram#19]
Browser blocks the CORS requests if index.html is opened with file://... . Suggest updating the README.md to indicate that the standalone site must be run from a web browser, and will not work from a file:// URL.

For example, from the "standalone" folder:
$>python -m SimpleHTTPServer

... then browse to http://localhost:8000

**Comment by chandanbn** [comment]
Thank you for the suggestion. I updated the readme with a pointer to a well written document from mozilla https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
