### ISSUE TITLE
Post to CVE.org button at bottom of Test Portal Editor tab

### ISSUE THREAD

**Issue by ccoffin** [Vulnogram/Vulnogram#199]
Using the Test Portal and reserved one CVE ID, then clicked on that ID to open the editor and populate the ID. Noted that the button at the very bottom of the Editor display reads "Post to CVE.org." This is incorrect and it should read "Post to Test Portal" just like at the top of the same Vulnogram page. I did not click the button to determine whether it posted the CVE ID to Test or production.

**Comment by chandanbn** [comment]
fixed
