### ISSUE TITLE
Should js/cve/render.js be in git?

### ISSUE THREAD

**Issue by iamamoose** [Vulnogram/Vulnogram#20]
Since js/cve/render.js is generated at build time should it be in git?

https://github.com/Vulnogram/Vulnogram/blob/master/public/js/cve/render.js

**Comment by chandanbn** [comment]
It shouldn't be in git, but then the server wouldn't run out of the box.
I need to add some code to generate such files on startup if they doesn't exist.

**Comment by chandanbn** [comment]
Fixed in 0.1.0. Javascript code is now auto generated from pug templates at server startup.
