### ISSUE TITLE
Vulnogram Generated Link to CAPECs Ends in 404 Error 

### ISSUE THREAD

**Issue by rsneff** [Vulnogram/Vulnogram#217]
When generating a CVE with Vulnogram and selecting a CAPEC, the generated CVE web link to the CAPEC ends ia 404 page error on the MITRE site.

e.g. the link that Vulnogram produces for CAPEC-216 is https://capec.mitre.org/data/definitions/CAPEC-216 which goes to an unavailable page.

It appears the CAPECs are now structured at  MITRE so that they no longer include 'CAPEC-' in the CAPEC page name.

So for the example above (CAPEC-216), the valid URL to it is now https://capec.mitre.org/data/definitions/216.html  (216.html not CAPEC-216.html as produced by Vulnogram). 

I've tried this on a number of selected CAPECs with the same result.

Thanks.

**Comment by chandanbn** [comment]
fixed now. There was a bug in CWEs too.
