### ISSUE TITLE
Package.json - typo?

### ISSUE THREAD

**Issue by RandallWilliams** [Vulnogram/Vulnogram#23]
Line 8 - node throws an error as written. I needed to add a space: between app.js and ;forever list

"start": "forever start --id 'vulnogram' --spinSleepTime 5000 --minUptime 2000 app.js;forever list",

"start": "forever start --id 'vulnogram' --spinSleepTime 5000 --minUptime 2000 app.js ;forever list",

**Comment by chandanbn** [comment]
Worked fine on Mac/Linux. I am guessing it could be a problem on windows interpretation of command separator ";". Hopefully fixed now, thank you!
