### ISSUE TITLE
API/ REST for Vulnogram? e.g. OData.

### ISSUE THREAD

**Issue by mpaujnpr01** [Vulnogram/Vulnogram#31]
Hi, would like to see a a REST interface / API to pull data from MongoDB / Vulnogram. 
Thanks for your consideration, 
Matt

**Comment by chandanbn** [comment]
There may be many off the shelf software that provide REST APIs for mongodb:
https://stackoverflow.com/questions/7386740/does-mongodb-have-a-native-rest-interface
