### ISSUE TITLE
Update render.js from cve.mitre.org to cve.org

### ISSUE THREAD

**Issue by ViperGeek** [Vulnogram/Vulnogram#50]
The CVE Working Group and MITRE are transitioning to an all-new CVE website at www.cve.org:

https://www.cve.org/Media/News/item/news/2021/09/29/Welcome-to-the-New-CVE

Please update public/js/cve/render.js to reference the new CVE ID URL format:

https://www.cve.org/CVERecord?id=CVE-yyyy-nnnnnn

**Comment by chandanbn** [comment]
fixed in 0.1.0 branch.
