### ISSUE TITLE
When exporting and importing json, the DATE_PUBLIC timestamp may get lost

### ISSUE THREAD

**Issue by MrSeccubus** [Vulnogram/Vulnogram#53]
When I was making my CNA "homework" I noticed that the DATE_PUBLIC does not always get populated when you update the json from clipboard or load it for file.

**Comment by MrSeccubus** [comment]
This seems to have to do with the DATA being stored as 
```
  "CVE_data_meta": {
    "DATE_PUBLIC": "",
```
On RESERVED entries and subsequently not being hidden in the UI.

**Comment by chandanbn** [comment]
If the pasted or imported value in DATE_PUBLIC is a valid ISO date I see it the GUI date picker shows it, but if it is invalid it resets it to empty string "" (and subsequently dropped while exporting the JSON).

I cant reproduce this (on Chrome) when there is a valid date.
