### ISSUE TITLE
make min target requires global install of uglifyjs

### ISSUE THREAD

**Issue by OneEricJohnson** [Vulnogram/Vulnogram#6]
uglifyjs not listed as a dependency. I didn't have it on my machine. Since I'm running MacPorts, which advises me to only install npm modules locally, when I did install uglifyjs, the Makefile still didn't work. I had to explicitly add node_modules/bin to my path in order to get this to work.

Since I'm not a node / npm expert, there may be an easy way to get this to work, but I couldn't figure it out.

**Comment by chandanbn** [comment]
It actually requires uglify-es (which has the same CLI command uglifyjs)
listed these as dependencies in package.json. Now running npm install should install all the required packages.
