### ISSUE TITLE
CVE V5 format incorrect rendering of advisory 

### ISSUE THREAD

**Issue by MrSeccubus** [Vulnogram/Vulnogram#62]
This input
![image](https://user-images.githubusercontent.com/1063278/160431694-f8b174c0-e13f-4a80-865e-52692efcca4d.png)

Leads to this advisory output:
![image](https://user-images.githubusercontent.com/1063278/160431792-ef030212-cf9d-49c4-8e30-d75b90efd111.png)
 But this input:
 
![image](https://user-images.githubusercontent.com/1063278/160431978-f4006e30-5e52-4046-92ba-5af1ed086ba8.png)

Correctly leads to this output:
![image](https://user-images.githubusercontent.com/1063278/160432095-bbcd891c-eff4-4b37-930a-3a0e5d1873ba.png)

**Comment by chandanbn** [comment]
Fixed in cve-session branch.
