### ISSUE TITLE
CVE5.0 CWE vs cepec

### ISSUE THREAD

**Issue by MrSeccubus** [Vulnogram/Vulnogram#63]
JSON format ofCWE is 
```
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "cweId": "CWE-129",
              "description": "CWE-129 Improper Validation of Array Index",
              "type": "CWE"
            }
          ]
        },
        {
          "descriptions": [
            {
              "lang": "en",
              "cweId": "CWE-77",
              "description": "CWE-77 Improper Neutralization of Special Elements used in a Command ('Command Injection')",
              "type": "CWE"
            }
          ]
        }
      ],
```

But capec is:
```
      "impacts": [
        {
          "capecId": "CAPEC-102",
          "descriptions": [
            {
              "lang": "en",
              "value": "CAPEC-102 Session Sidejacking"
            }
          ]
        },
        {
          "capecId": "CAPEC-107",
          "descriptions": [
            {
              "lang": "en",
              "value": "CAPEC-107 Cross Site Tracing"
            }
          ]
        }
      ],
```

Since cweId and type are not language specific, shouldn't they be outside the descriptions array?

**Comment by chandanbn** [comment]
In Vulnogram these two fields appear as editable drop-downs. As you type letters in the box, the list of suggestions gets smaller. The suggested line is what that goes into value field, and capecId or cweId is computed based on value. Removing the IDs from being shown in drop-downs may make it complicated in few use cases. While this is redundant, I feel it is OK given other benefits (being able to see the ID in the drop-down itself).

**Comment by MrSeccubus** [comment]
This isn’t about the UI, but about how it appears in the JSON. 

I believe it should reder just like impacts:
```
impacts : [
{
type: ‘CWE’,
cweId: ‘CWE-123’,
descriptions: [
{
lang: ‘en’,
Description: ….
```

If this is how it is in the schema, I’ll raise it with the schema project, but it could be a vulnogram bug too.
