### ISSUE TITLE
"impacts" requirement in Vulnogram vs. CVE JSON 5.0 Schema

### ISSUE THREAD

**Issue by dkoehler-boschpsirt** [Vulnogram/Vulnogram#67]
Vulnogram considers CVEs without the "impacts" property as invalid, however it is actually not a required field according to the CVE JSON schema (but if it is provided, it must contain at least one item): https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/CVE_JSON_5.0_schema.json#L550-L555

**Comment by chandanbn** [comment]
Yes done on purpose to reduce the number of clicks to add an impact and to balance the UI layout.
Otherwise it shows as an empty list with an add button and then you have to add it.
