### ISSUE TITLE
Handling of "versionType" field for single versions

### ISSUE THREAD

**Issue by dkoehler-boschpsirt** [Vulnogram/Vulnogram#68]
Vulnogram currently allows to provide a "versionType" for single versions (vs.  version ranges).
Example:
```json
      "affected": [
        {
          "vendor": "Example Company",
          "product": "Example Product",
          "versions": [
            {
              "status": "affected",
              "version": "1.2.3",
              "versionType": "custom"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ]
```
According to the CVE JSON 5.0 schema, this is actually prohibited and JSON schema validators will complain: https://github.com/CVEProject/cve-schema/blob/1e12cfbccbe876b2d6966fb7d6b3ca38eb1aea89/schema/v5.0/CVE_JSON_5.0_schema.json#L283-L284

**Comment by chandanbn** [comment]
fixed, it now throws an error for such cases.
