### ISSUE TITLE
Using relative path for JavaScript and CSS files.

### ISSUE THREAD

**Issue by sei-vsarvepalli** [Vulnogram/Vulnogram#72]
Most of the pug files seem to use the convention of assuming root directory for the Vulnogram standalone install.  It may be good to convert all these to relative paths.  Below is an example of such a change. 
```
--- a/default/cve5/edit.pug
+++ b/default/cve5/edit.pug
@@ -48,5 +48,5 @@ block customtabs
         input.tab(name='tabs', type='radio', id='cveApiTab', value="6")
         label.lbl(for='cveApiTab') CVE Portal
         .wht.fil.bor.pad
-            script(src="/js/tablesort.min.js")
+            script(src="./js/tablesort.min.js")
             #cvePortal

```

Is there any concern in doing this change for all files so the install of the standalone setup can be  on a web server with path like /vulnogram/ or behind a reverse-proxy or behind an AWS load balancer.

Thanks
Vijay

**Comment by chandanbn** [comment]
Fixed in CVE-session branch.
