### ISSUE TITLE
wysihtml possibly unmaintained or has embargoed CVE Record?

### ISSUE THREAD

**Issue by ElectricNroff** [Vulnogram/Vulnogram#79]
https://github.com/Vulnogram/Vulnogram/tree/82d3fb3ff0fbdc81ba605b9b5f48f98aa09d36c2/public/js/wy
indicates that wysihtml v0.5.5 is used. Is there any information about a potential https://cwe.mitre.org/data/definitions/1104.html risk?

https://github.com/Voog/wysihtml/issues/402 was posted by the https://www.cve.org/PartnerInformation/ListofPartners/partner/@huntrdev CNA on 2021-12-09 but there's no response within that issue and https://github.com/Voog/wysihtml apparently hasn't had public development since then.

**Comment by chandanbn** [comment]
I am not aware of any security issues, but unmaintained status is one reason for #57. Closing this as a duplicate.
