### ISSUE TITLE
Invalid JSON v5 if versionType is blank

### ISSUE THREAD

**Issue by iamamoose** [Vulnogram/Vulnogram#80]
When adding Versions, if a lessThan (or similar comparison) is included then a versionType is required by the schema, but vulnogram doesn't warn on this and you end up with non-validating json:

i.e. 
```
      "affected": [
        {
          "versions": [
            {
              "status": "affected",
              "version": "3.0.0",
              "lessThan": "3.0.3"
            }
          ],
          "defaultStatus": "unaffected"
        }
```

**Comment by chandanbn** [comment]
fixed, it nows show errors for those cases.
