### ISSUE TITLE
Toggle between local timezone and UTC for public_date input

### ISSUE THREAD

**Issue by tyhicks** [Vulnogram/Vulnogram#9]
Issue #1 was fixed so that the date_public field is always converted from the client's local time zone to UTC. This should meet the needs of many users but I think there are likely a number of CNAs that use UTC for their internal database. It would be great if there was a way to toggle between local time and UTC when inputting the date_public value.

**Comment by chandanbn** [comment]
I should make the timezone label something like a dropdown.

Times are displayed in UTC under the Source or JSON tabs. You could switch to Source tab and edit the time in UTC.

**Comment by tyhicks** [comment]
> I should make the timezone label something like a dropdown.

That would certainly do the trick.

> Times are displayed in UTC under the Source or JSON tabs. You could switch to Source tab and edit the time in UTC.

Ah, thanks for the workaround!
