### ISSUE TITLE
CVE 5.0 CVE Portal test login attempt results in 'csClient is undefined'

### ISSUE THREAD

**Issue by zmanion** [Vulnogram/Vulnogram#98]
Attempting to log in with test credentials, fill out information on portal tab, click Login button, error dialog is 'csClient is undefined'. Tried with vulngram.github.io and local standalone server using 0.1.0 branch.

Attempting to record a demo for the November 2 CVE Services workshop.

**Comment by chandanbn** [comment]
Could be a caching problem on the browser. Does it happen in incognito mode?

The underlaying scripts were refactored. An old cached script or cookie could bring up error. Few others reported seeing errors, but refreshing/restarting the browser made the problem go away.

**Comment by zmanion** [comment]
Sorry it's working now. I did test in icognito before filing the issue.

**Comment by zmanion** [comment]
FWIW, macos, Firefox private window: can't log in, Chrome private window: can log in.

**Comment by chandanbn** [comment]
Firefox doesn't support spawning ServiceWorkers in Private mode https://bugzilla.mozilla.org/show_bug.cgi?id=1320796

Vulnogram uses them to emulate a session to CVE API connection and to share consistent state between browser tabs.

For now it just shows a warning message about browser not having the service workers feature. It needs a better fall-back mechanism.
